import { Nunito_Sans } from "next/font/google";
import ReduxProvider from "../ReduxProvider";
import "./globals.css";
import { Toaster } from "react-hot-toast"; 

const nunito = Nunito_Sans({
  subsets: ["latin"],
  weight: ["400", "600", "700"],
  display: "swap",
});

export const metadata = {
  title: "Task Processor",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`antialiased ${nunito.className}`}>
        <ReduxProvider>{children}
          <Toaster position="top-center" autoClose={3000} hideProgressBar={false} newestOnTop={false} closeOnClick rtl={false} pauseOnFocusLoss draggable pauseOnHover />
        </ReduxProvider>
      </body>
    </html>
  );
}
